In [20]:
# ! pip install openpyxl 
# import openpyxl
# import numpy as np
import pandas as pd
import random

In [26]:
path = "../data/data.xlsx"
ads_table = pd.read_excel(path, sheet_name = 0, header = 1)
mod_table = pd.read_excel(path, sheet_name = 1)

In [27]:
ads_table_dropped = ads_table.dropna()
ads_table_dropped = ads_table_dropped.reset_index(drop=True)
ads_table_dropped

,p_date,ad_id,delivery_country,queue_market,punish_num,latest_punish_begin_date,ad_revenue,avg_ad_revenue,start_time,baseline_st,product_line,task_type_en
0,20230807,1747578422390810,US,USCA,1.0,2023-07-24,5132.1700,4795.2500,2022-10-24 14:36:00,1.78,Auction Ads,auction_relation
1,20230807,1758543228094480,SA,MENA,1.0,2023-06-14,1976.2500,1063.7670,2023-02-22 15:50:00,1.67,RIE,Ad Group Recall (Merged)
2,20230807,1738303151826990,AU,AU,2.0,2023-07-24,1.7355,5.3650,2022-07-14 05:00:00,1.84,Auction Ads,auction_relation
3,20230807,1738304016410620,NZ,NZ,2.0,2023-07-24,1.5250,5.3650,2022-07-14 05:17:00,1.58,Auction Ads,auction_relation
4,20230807,1738304421208090,NZ,NZ,2.0,2023-07-24,0.7889,5.3650,2022-07-14 05:24:00,1.58,Auction Ads,auction_relation
...,...,...,...,...,...,...,...,...,...,...,...,...
1280,20230807,1773610467447840,NO,Others,1.0,2023-06-26,0.3700,4.5148,2023-08-07 22:20:00,1.56,Auction Ads,auction_all
1281,20230807,1773560585140270,KH,KH,1.0,2023-05-16,0.1452,0.4317,2023-08-07 22:00:00,1.50,Auction Ads,auction_relation
1282,20230807,1773559790111770,KH,KH,1.0,2023-05-16,0.1352,0.4317,2023-08-07 22:00:00,1.50,Auction Ads,auction_relation
1283,20230807,1773595125935120,BR,BR,1.0,2023-07-17,0.0000,26.7034,2023-08-08 03:00:00,1.43,Non-Auction Ads,R&F
1284,20230807,1773574220965890,HU,Others,1.0,2023-05-14,5.5455,56.1366,2023-08-07 23:00:00,1.53,Non-Auction Ads,R&F

In [28]:
def fake_score():
    return random.random()

ads_table_dropped['score'] = 0
ads_table_dropped['score'] = ads_table_dropped['score'].apply(lambda x: fake_score())
ads_table_dropped

,p_date,ad_id,delivery_country,queue_market,punish_num,latest_punish_begin_date,ad_revenue,avg_ad_revenue,start_time,baseline_st,product_line,task_type_en,score
0,20230807,1747578422390810,US,USCA,1.0,2023-07-24,5132.1700,4795.2500,2022-10-24 14:36:00,1.78,Auction Ads,auction_relation,0.471150
1,20230807,1758543228094480,SA,MENA,1.0,2023-06-14,1976.2500,1063.7670,2023-02-22 15:50:00,1.67,RIE,Ad Group Recall (Merged),0.299850
2,20230807,1738303151826990,AU,AU,2.0,2023-07-24,1.7355,5.3650,2022-07-14 05:00:00,1.84,Auction Ads,auction_relation,0.059457
3,20230807,1738304016410620,NZ,NZ,2.0,2023-07-24,1.5250,5.3650,2022-07-14 05:17:00,1.58,Auction Ads,auction_relation,0.662106
4,20230807,1738304421208090,NZ,NZ,2.0,2023-07-24,0.7889,5.3650,2022-07-14 05:24:00,1.58,Auction Ads,auction_relation,0.619513
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1280,20230807,1773610467447840,NO,Others,1.0,2023-06-26,0.3700,4.5148,2023-08-07 22:20:00,1.56,Auction Ads,auction_all,0.008706
1281,20230807,1773560585140270,KH,KH,1.0,2023-05-16,0.1452,0.4317,2023-08-07 22:00:00,1.50,Auction Ads,auction_relation,0.331948
1282,20230807,1773559790111770,KH,KH,1.0,2023-05-16,0.1352,0.4317,2023-08-07 22:00:00,1.50,Auction Ads,auction_relation,0.464522
1283,20230807,1773595125935120,BR,BR,1.0,2023-07-17,0.0000,26.7034,2023-08-08 03:00:00,1.43,Non-Auction Ads,R&F,0.930513
1284,20230807,1773574220965890,HU,Others,1.0,2023-05-14,5.5455,56.1366,2023-08-07 23:00:00,1.53,Non-Auction Ads,R&F,0.709753

## Queuing

In [29]:
mod_table

,moderator,market,Productivity,Utilisation %,handling time,accuracy
0,1689841547143170,"[""SA"", ""OM"", ""BH"", ""QA"", ""JO"", ""IQ"", ""KW"", ""EG...",286.217674,0.812403,123549,-
1,1686755036370945,"[""RO""]",174.560000,0.704833,25547,0.959
2,1741913197768705,"[""VN""]",334.376000,0.819167,50794,1
3,1743415203890193,"[""MX"", ""UY"", ""CL"", ""AR"", ""CO"", ""EC"", ""PE"", ""BR""]",452.277500,0.775474,89626,0.941
4,1710346282427393,"[""PH""]",612.312500,0.843229,98066,0.887
...,...,...,...,...,...,...
1409,1734911746733057,"[""US"", ""CA""]",180.750000,0.685469,79210,0.86
1410,1694737747315714,"[""TH""]",542.360000,0.890927,49664,0.958
1411,1730993346971650,"[""RO""]",320.960000,0.843042,73769,0.967
1412,1707706649725953,"[""GB""]",283.261333,0.846072,90975,0.865
1413,1772302280493057,"[""GB""]",NaN,NaN,0,0.909

In [24]:
n = len(pd.unique(mod_table['moderator']))
n

KeyError: 'moderator'

In [9]:
## First condition check for market

Hello